# This is a TOML document.

title = "CONFIG CharLSTMLM"

path = '/home/cluster/evhuber/data/wiki_no_unk_short'
model_dir = 'try_run/models'
log_path = 'try_run/logger'
nr_epochs = 10
bs = 128
seq_len = 15
word_length = 10

l_r = 0.001

[wordmodel]
embedding_size = 300
hidden_size = 200
nlayers = 2
dropout = 0.1

[charmodel]
embedding_size = 100
hidden_size = 100
dropout = 0.1
nlayers = 1

[generator]

embedding_size = 100
hidden_size = 100
nlayers = 1
dropout = 0.1